# Set to true to add reviewers to pull requests
addReviewers: true

# Set addAssignees to 'author' to set the PR creator as the assignee.
addAssignees: author

filterLabels:
  # Run
  #include:
  #- my_label_te
  # Not run
  exclude:
    - ":x: DO_NOT_MERGE :x:"
    - "work_in_progress :construction:"

# A list of reviewers to be added to pull requests (GitHub user name)
reviewers:
  - j-abi
  - khouloudsa
  - jsc-spideo

# A number of reviewers added to the pull request
# Set 0 to add all the reviewers (default: 0)
numberOfReviewers: 2